name: Notify

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Send notification
        run: |
          # 基本转义处理
          MESSAGE=$(echo '${{ github.event.head_commit.message }}' | sed 's/"/\\"/g')
          AUTHOR="${{ github.event.head_commit.author.name || github.actor }}"
          
          curl -X POST \
            "https://${{ secrets.APIURL }}/send_group_msg" \
            -H "Authorization: Bearer ${{ secrets.APITOKEN }}" \
            -H "Content-Type: application/json" \
            -d "{
              \"group_id\": \"1053570434\",
              \"message\": [
                {
                  \"type\": \"text\",
                  \"data\": {
                    \"text\": \"📢 主分支已更新！\n\n👤 作者: $AUTHOR\n📝 描述: $MESSAGE\n🔗 提交: ${{ github.sha }}\"
                  }
                }
              ]
            }"
