name: Notify

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Send notification
        uses: actions/http-client@v1
        with:
          url: 'https://${{ secrets.APIURL }}/send_group_msg'
          method: 'POST'
          headers: |
            Authorization: Bearer ${{ secrets.APITOKEN }}
            Content-Type: application/json
          body: |
            {
              "group_id": "1053570434",
              "message": [
                {
                  "type": "text",
                  "data": {
                    "text": "主分支已更新！最新提交: ${{ github.sha }}"
                  }
                }
              ]
            }
