name: Notify

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Send notification
        run: |
          curl -X POST \
            "https://${{ secrets.APIURL }}/send_group_msg" \
            -H "Authorization: Bearer ${{ secrets.APITOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{
                 "group_id": "1053570434",
                 "message": [
                   {
                     "type": "text",
                     "data": {
                       "text": "📢 主分支已更新！\n\n👤 作者: ${{ github.actor }}\n📝 描述: ${{ github.event.head_commit.message }}\n🔗 提交: ${{ github.sha }}"
                     }
                   }
                 ]
               }'
